export const GET_TICKETS = 'GET_TICKETS';
export const SAVE_TICKETS = 'SAVE_TICKETS';
export const GET_EXCHANGE_RATE = 'GET_EXCHANGE_RATE';
export const SAVE_EXCHANGE_RATE = 'SAVE_EXCHANGE_RATE';
export const SET_CURRENCY = 'SET_CURRENCY';
export const CHANGE_STATUS_CHECKBOX = 'CHANGE_STATUS_CHECKBOX';
export const CHANGE_STATUS_FOR_ALL = 'CHANGE_STATUS_FOR_ALL';